/// <reference types="node" />

import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";
import { createHash } from "node:crypto";

import { decimalFromHex, sha256Hex, toHex } from "../../src/worker/pki/utils/conversion";

const CERT_DER_URL = new URL("../fixtures/pki/certs/leaf/leaf-full.cert.der", import.meta.url);
const CERT_SERIAL_HEX = "0A46A242EAF2D833B7552DA70D66D81D435123A9";

test("sha256Hex matches the digest generated by openssl", async () => {
  const certBytes = await readFile(CERT_DER_URL);
  const digest = await sha256Hex(certBytes);
  const expected = createHash("sha256").update(certBytes).digest("hex");
  assert.equal(digest, expected);
});

test("toHex converts binary to lower-case hex", () => {
  const bytes = new Uint8Array([0x0a, 0x46, 0xa2]);
  assert.equal(toHex(bytes), "0a46a2");
});

test("decimalFromHex converts serial numbers from hex", () => {
  const decimal = decimalFromHex(CERT_SERIAL_HEX);
  const expected = BigInt(`0x${CERT_SERIAL_HEX}`).toString(10);
  assert.equal(decimal, expected);
});

test("decimalFromHex returns null on invalid input", () => {
  assert.equal(decimalFromHex("not-hex"), null);
  assert.equal(decimalFromHex(null), null);
});
